### ISSUE TITLE
[bug] Publishing and element fails 

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/beta#542] opened 2016-10-18 12:18 UTC
Not sure if this is NPM related (since I do not have bower on this component) but the publish page will not accept my component submit.

Tested in Chrome 52 on Macbook pro (Sierra OSX) 
#### Steps to reproduce:
1. click/tap on publish button
2. enter `Nevraeka/star-rating` in the Github input field
3. Complete ReCaptcha
4. click/tap on publish button
#### Actual outcome
- After the initial submit and on trying to load the page again reveals thousands of `frameURI` errors on page load and page freezes at some point. 
- spinner keeps spinning on the publish button
- page does not visibly change or redirect
#### Console Errors

<img width="721" alt="screen shot 2016-10-18 at 8 14 29 am" src="https://cloud.githubusercontent.com/assets/647043/19477278/620835a0-950b-11e6-9903-e6e07341e65f.png">

**Comment by Nevraeka** [comment] 2016-10-18 12:19
initially I had 400 errors for the API (hence the label) cc/ @samuelli

**Comment by samuelli** [comment] 2016-10-18 13:00
We don't currently support NPM. I'm unsure of the implications of the Yarn announcement.

I repro'd the 400's, which are from us polling the API till we know something - we need to show better errors in those cases.

I don't think the `frameURI` errors are from this site though. Looks like a Chrome extension error'ing.

**Comment by samuelli** [comment] 2016-11-02 05:10
Hey @Nevraeka!

Closing this issue as NPM/Yarn support is tracked https://github.com/webcomponents/beta/issues/531

The page should show better errors now and I could not reproduce the `frameURIs` errors.

**Closed by samuelli** 2016-11-02 05:10 UTC
Labels: API
