### ISSUE TITLE
Collection view only 10 elements

### ISSUE THREAD

**Issue by JosefJezek** [webcomponents/beta#595] opened 2016-11-01 10:53 UTC
[Origin page](https://beta.webcomponents.org/collection/StartPolymer/awesome-buttons)

Could you help me?

**Comment by JosefJezek** [comment] 2016-11-01 10:56
And here https://beta.webcomponents.org/collection/StartPolymer/awesome-charts

Only 7 of 9 elements

**Comment by abdonrd** [comment] 2016-11-01 11:06
Fixed with https://github.com/webcomponents/beta/pull/591 :)

**Comment by dstockwell** [comment] 2016-11-01 22:42
Collections only list elements that have been successfully added:

eg. https://beta.webcomponents.org/element/PolymerEl/multi-chart => `Could not detect an OSI approved license on GitHub or in master/bower.json`

**Comment by dstockwell** [comment] 2016-11-02 01:25
Closing since this is working as intended, but please comment if I missed something.

**Closed by dstockwell** 2016-11-02 01:25 UTC

**Comment by JosefJezek** [comment] 2016-11-02 03:16
This elements have license in bower.json, but are not showing...

https://beta.webcomponents.org/element/robdodson/chart-elements
https://github.com/robdodson/chart-elements/blob/master/bower.json#L16

https://beta.webcomponents.org/element/1000ch/social-button
https://github.com/1000ch/social-button/blob/gh-pages/bower.json#L13

**Comment by dstockwell** [comment] 2016-11-02 03:28
https://beta.webcomponents.org/element/1000ch/social-button seems to be working now, when it was first added we only supported the master branch.

We don't have the capability to understand licenses behind URLs linked from bower.json as in robdodson/chart-elements, only SPDX identifiers.

**Comment by JosefJezek** [comment] 2016-11-02 04:16
Could you add support for URL? Example

`"license": "MIT (https://github.com/StartPolymer/license)"`

https://github.com/bower/spec/blob/master/json.md#license

**Comment by JosefJezek** [comment] 2016-11-02 04:27
https://github.com/StartPolymer/s-html/blob/master/bower.json#L19

**Comment by samuelli** [comment] 2016-11-02 04:34
@JosefJezek: bower spec is a SPDX identifier or a URL. If the license is based on a standard license, its best to specify what type of license it is.

If its common, we can manually white-list a license: https://github.com/webcomponents/beta/blob/master/src/licenses.py#L5

**Comment by JosefJezek** [comment] 2016-11-02 04:44
@samuelli ok
