### ISSUE TITLE
Element page versions don't fully work

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#347] opened 2016-10-05 00:08 UTC
Repro steps

1. Go to https://beta.webcomponents.org/element/PolymerElements/paper-icon-button/v1.1.2/demo/demo/index.html
2. Click out

Looks like the route splitting is failing and hence making the wrong ajax requests

**Comment by dstockwell** [comment] 2016-10-05 04:31
Dupe of https://github.com/webcomponents/beta/issues/277 ?

**Closed** 2016-10-05 04:35 UTC
