### ISSUE TITLE
Support package.json instead of bower.json as well

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/beta#748] opened 2016-12-26 09:04 UTC
Hey,

I know that Polymer relies on bower, but much of the front-end community has moved entirely to npm. When developing vanilla js custom elements, there is actually no reason to support bower for many developers.

Therefore it would be very good if one could publish a component with a package that has only a **package.json** and no **bower.json**.

**Comment by dstockwell** [comment] 2017-01-06 03:06
Dupe of #531

**Closed by dstockwell** 2017-01-06 03:06 UTC
Labels: duplicate

**Comment by lukasoppermann** [comment] 2017-01-07 11:46
For me it was two different things. One is the install instructions, one the registry showing the info from package.json. However, I will add this part to the other issue.
