### ISSUE TITLE
Publish: recaptcha sometimes missing from publish page

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#455] opened 2016-10-11 20:21 UTC
[Origin page](https://beta.webcomponents.org/publish)

I've noticed the recaptcha does not show up sometimes when navigating to the publish page:

<img width="928" alt="screen shot 2016-10-11 at 1 19 47 pm" src="https://cloud.githubusercontent.com/assets/238208/19287147/6de3b2a6-8fb5-11e6-83ec-9632c80792d8.png">

I didn't realize it was there and hit "publish". Nothing happened :( 

The publish button could be disabled until the recaptcha is ready.

**Comment by samuelli** [comment] 2016-10-11 23:10
Sorry about that! Hit refresh as a workaround.
Dupe of #439

**Closed by samuelli** 2016-10-11 23:10 UTC
Labels: Feedback
